//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagPlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagPlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Tags&gt;
        ///  &lt;FeelingTags&gt;
        ///    &lt;Tag&gt;怀旧&lt;/Tag&gt;
        ///    &lt;Tag&gt;清新&lt;/Tag&gt;
        ///    &lt;Tag&gt;浪漫&lt;/Tag&gt;
        ///    &lt;Tag&gt;性感&lt;/Tag&gt;
        ///    &lt;Tag&gt;伤感&lt;/Tag&gt;
        ///    &lt;Tag&gt;治愈&lt;/Tag&gt;
        ///    &lt;Tag&gt;放松&lt;/Tag&gt;
        ///    &lt;Tag&gt;孤独&lt;/Tag&gt;
        ///    &lt;Tag&gt;感动&lt;/Tag&gt;
        ///    &lt;Tag&gt;兴奋&lt;/Tag&gt;
        ///    &lt;Tag&gt;快乐&lt;/Tag&gt;
        ///    &lt;Tag&gt;安静&lt;/Tag&gt;
        ///    &lt;Tag&gt;思念&lt;/Tag&gt;
        ///  &lt;/FeelingTags&gt;
        ///  &lt;RegionTags&gt;
        ///    &lt;Tag&gt;华语&lt;/Tag&gt;
        ///    &lt;Tag&gt;日语&lt;/Tag&gt;
        ///    &lt;Tag&gt;韩语&lt;/Tag&gt;
        ///    &lt;Tag&gt;粤语&lt;/Tag&gt;
        ///    &lt;Tag&gt;小语种&lt;/Tag&gt;
        ///  &lt;/RegionTags&gt;
        ///  &lt;SceneTags&gt;
        ///    &lt;Tag&gt;清晨&lt;/Tag&gt;
        ///    &lt;Tag&gt;夜晚&lt;/Tag&gt;        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SongTags {
            get {
                return ResourceManager.GetString("SongTags", resourceCulture);
            }
        }
    }
}
